name: tellgo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0
  circle_flags: ^5.0.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # device_preview: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/hero/
    - assets/icons/
    - assets/icons/profile/
    - assets/icons/login/
    - assets/icons/profile/go_points/
    - assets/icons/bottomNav/
    - assets/background.png